// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define SERIF_12_FONT_ID (778531645)
#define SERIF_14_FONT_ID (-928381217)
#define SERIF_16_FONT_ID (17214534)
#define SERIF_18_FONT_ID (840051567)
#define SANS_12_FONT_ID (1597191560)
#define SANS_14_FONT_ID (-1413326613)
#define SANS_16_FONT_ID (116566294)
#define SANS_18_FONT_ID (-348426591)
#define UI_10_FONT_ID (-549000461)
#define UI_12_FONT_ID (1085916491)
#define SMALL_FONT_ID (145012156)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(SERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
